version: "3"


services:

  app:
    container_name: app
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app:rw
    env_file: .env # If not .env file in the directory, it will not be loaded. Generate .env from .env_example
    command: "flask run -h 0.0.0.0 -p 5000"